pub const NEW_STATUS: i32 = 0x1F0; 

pub const FIGHTER_GOOMBA_STATUS_KIND_SPECIAL_LW_POUND: i32 = 0x1E3;
pub const FIGHTER_GOOMBA_STATUS_KIND_SPECIAL_LW_LANDING: i32 = 0x1E4;
pub const FIGHTER_GOOMBA_STATUS_KIND_SPECIAL_LW_HIT: i32 = 0x1E5;

pub const GOOMBA_FLAG_START: i32 = 0x200000E8;
pub const GOOMBA_INT_START: i32 = 0x100000BF;
pub const GOOMBA_FLOAT_START: i32 = 0x4C;

pub const FIGHTER_GOOMBA_INSTANCE_FLAG_SUPERLEAF_VISIBLE: i32 = GOOMBA_FLAG_START;
pub const FIGHTER_GOOMBA_INSTANCE_FLAG_SPECIAL_S_DISABLE_HOP: i32 = GOOMBA_FLAG_START+1;

pub const FIGHTER_GOOMBA_SPECIAL_N_FLAG_CAN_GEN: i32 = 0x21000017;
pub const FIGHTER_GOOMBA_SPECIAL_N_FLAG_SHOOT: i32 = 0x21000018;

pub const FIGHTER_GOOMBA_SPECIAL_S_FLAG_HAS_HOP: i32 = 0x2100000C;
pub const FIGHTER_GOOMBA_SPECIAL_S_FLAG_HOP: i32 = 0x2100000D;
pub const FIGHTER_GOOMBA_SPECIAL_S_FLAG_CONTROL: i32 = 0x2100000E;
pub const FIGHTER_GOOMBA_SPECIAL_S_FLAG_GRAVITY: i32 = 0x2100000F;
pub const FIGHTER_GOOMBA_SPECIAL_S_FLAG_REFLECT_SFX: i32 = 0x21000010;

pub const FIGHTER_GOOMBA_SPECIAL_HI_FLAG_REVERSE_LR: i32 = 0x2100000D;
pub const FIGHTER_GOOMBA_SPECIAL_HI_FLAG_DECIDE_DIRECTION: i32 = 0x2100000E;
pub const FIGHTER_GOOMBA_SPECIAL_HI_FLAG_ENABLE_LANDING: i32 = 0x2100000F;
pub const FIGHTER_GOOMBA_SPECIAL_HI_FLAG_ENABLE_BOUNCE: i32 = 0x21000010;
pub const FIGHTER_GOOMBA_SPECIAL_HI_FLAG_DISABLE_MOTION_ANGLE: i32 = 0x21000010;
pub const FIGHTER_GOOMBA_SPECIAL_HI_FLOAT_ANGLE: i32 = 0x1000007;

pub const FIGHTER_GOOMBA_SPECIAL_LW_FLAG_FROM_GROUND: i32 = 0x2100000D;
pub const FIGHTER_GOOMBA_SPECIAL_LW_FLAG_LANDING_ENABLE: i32 = 0x2100000E;
pub const FIGHTER_GOOMBA_SPECIAL_LW_FLAG_FALL: i32 = 0x2100000F;
pub const FIGHTER_GOOMBA_SPECIAL_LW_INT_COUNT: i32 = 0x11000007;

pub const FIGHTER_GOOMBA_SPECIAL_LW_SPIKE_FRAME: f32 = 20.0;
/*
FIGHTER_PICHU_GENERATE_ARTICLE_CLOUD: 0x3 -
FIGHTER_PICHU_GENERATE_ARTICLE_DENGEKI(Grounded tjolt): 0x1 - 
FIGHTER_PICHU_GENERATE_ARTICLE_DENGEKIDAMA(tjolt): 0x0 -
FIGHTER_PICHU_GENERATE_ARTICLE_MONSTERBALL: 0x5 -
FIGHTER_PICHU_GENERATE_ARTICLE_SPECIALUPDUMMY: 0x2 -
FIGHTER_PICHU_GENERATE_ARTICLE_VORTEX (?): 0x4 -
*/
pub const FIGHTER_GOOMBA_GENERATE_ARTICLE_SHIP: i32 = 0x5;
pub const FIGHTER_GOOMBA_GENERATE_ARTICLE_LAST: i32 = 0x6;
pub static mut FIGHTER_GOOMBA_GENERATE_ARTICLE_ACCESSORIES: i32 = 0x0;
pub static mut FIGHTER_GOOMBA_GENERATE_ARTICLE_REDSHELL: i32 = 0x0;
/*
    WEAPON_MIISWORDSMAN_CHAKRAM_INSTANCE_WORK_ID_FLAG_1F_FALL: 0x2000000A,
    WEAPON_MIISWORDSMAN_CHAKRAM_INSTANCE_WORK_ID_FLAG_ENABLE_FALL: 0x20000009,
    WEAPON_MIISWORDSMAN_CHAKRAM_INSTANCE_WORK_ID_FLAG_FLICK: 0x20000008,
    WEAPON_MIISWORDSMAN_CHAKRAM_INSTANCE_WORK_ID_FLOAT_ANGLE: 0x4,
    WEAPON_MIISWORDSMAN_CHAKRAM_INSTANCE_WORK_ID_FLOAT_FALL_ANGLE: 0x5,
    WEAPON_MIISWORDSMAN_CHAKRAM_INSTANCE_WORK_ID_FLOAT_SPEED: 0x3,
    WEAPON_MIISWORDSMAN_CHAKRAM_STATUS_KIND_FALL: 0x5,
    WEAPON_MIISWORDSMAN_CHAKRAM_STATUS_KIND_FLY: 0x2,
    WEAPON_MIISWORDSMAN_CHAKRAM_STATUS_KIND_HAVED: 0x1,
    WEAPON_MIISWORDSMAN_CHAKRAM_STATUS_KIND_HOP: 0x3,
    WEAPON_MIISWORDSMAN_CHAKRAM_STATUS_KIND_NUM: 0x6,
    WEAPON_MIISWORDSMAN_CHAKRAM_STATUS_KIND_START: 0x0,
    WEAPON_MIISWORDSMAN_CHAKRAM_STATUS_KIND_STICK: 0x4,
     */
pub const ACCESSORIES_STATUS_KIND_HAVED: i32 = 0x0;
pub const ACCESSORIES_STATUS_KIND_EJECTED: i32 = 0x1;
pub const ACCESSORIES_INSTANCE_FLOAT_LIFE: i32 = 0x6;

pub const REDSHELL_STATUS_KIND_HAVED: i32 = 0x0;
pub const REDSHELL_STATUS_KIND_SHOOT: i32 = 0x1;
pub const REDSHELL_STATUS_KIND_FURAFURA: i32 = 0x2;

pub const REDSHELL_INSTANCE_FLOAT_BRAKE_X: i32 = 0x6;
pub const REDSHELL_INSTANCE_FLOAT_SPEED: i32 = 0x3;
pub const REDSHELL_INSTANCE_FLAG_BIG_BRAKE: i32 = 0x2000000A;
pub const REDSHELL_INSTANCE_FLAG_FRIENDLY_FIRE: i32 = 0x2000000B;
pub const REDSHELL_INSTANCE_INT_RESPAWN_ATTACK_COUNTDOWN: i32 = 0x1000000A;