pub const NEW_STATUS: i32 = 0x1F0; 

/*
FIGHTER_PICHU_INSTANCE_WORK_ID_FLAG_STRANS_1: 0x200000E6,
    FIGHTER_PIKMIN_INSTANCE_WORK_ID_FLOAT_SPECIAL_HI_FRAME: 0x4C,
    FIGHTER_PICHU_INSTANCE_WORK_ID_INT_AIR_MOT: 0x100000BE,
     */
pub const GOOMBA_FLAG_START: i32 = 0x200000E8;
pub const GOOMBA_INT_START: i32 = 0x100000BF;
pub const GOOMBA_FLOAT_START: i32 = 0x4C;

pub const FIGHTER_GOOMBA_INSTANCE_FLAG_SUPERLEAF_VISIBLE: i32 = GOOMBA_FLAG_START;
pub const FIGHTER_GOOMBA_INSTANCE_FLAG_SPECIAL_S_DISABLE_HOP: i32 = GOOMBA_FLAG_START+1;

/*
FIGHTER_PIKACHU_STATUS_WORK_ID_FLAG_SKULL_BASH_HIT: 0x21000010,
 */
pub const FIGHTER_GOOMBA_SPECIAL_S_HAS_HOP: i32 = 0x2100000C;
pub const FIGHTER_GOOMBA_SPECIAL_S_HOP: i32 = 0x2100000D;
pub const FIGHTER_GOOMBA_SPECIAL_S_CONTROL: i32 = 0x2100000E;

/*
FIGHTER_PICHU_GENERATE_ARTICLE_CLOUD: 0x3 -
FIGHTER_PICHU_GENERATE_ARTICLE_DENGEKI(Grounded tjolt): 0x1 - 
FIGHTER_PICHU_GENERATE_ARTICLE_DENGEKIDAMA(tjolt): 0x0 -
FIGHTER_PICHU_GENERATE_ARTICLE_MONSTERBALL: 0x5 -
FIGHTER_PICHU_GENERATE_ARTICLE_SPECIALUPDUMMY: 0x2 -
FIGHTER_PICHU_GENERATE_ARTICLE_VORTEX (?): 0x4 -
*/
pub const FIGHTER_GOOMBA_GENERATE_ARTICLE_SHIP: i32 = 0x5;
pub const FIGHTER_GOOMBA_GENERATE_ARTICLE_LAST: i32 = 0x6;
pub static mut FIGHTER_GOOMBA_GENERATE_ARTICLE_ACCESSORIES: i32 = 0x0;